[{"name": "test.test_vector_lengths.VectorLengths.test_content", "status": "passed", "message": "", "passed": true, "points": ["p02-14.1"], "backtrace": []}, {"name": "test.test_vector_lengths.VectorLengths.test_main", "status": "errored", "message": "axis 1 is out of bounds for array of dimension 1", "passed": false, "points": ["p02-14.1"], "backtrace": ["  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\isaul\\Documents\\Intro to ML\\mooc-fi\\mooc-data-analysis-with-python-2024-2025\\part02-e14_vector_lengths\\test\\test_vector_lengths.py\", line 60, in test_main\n    main()\n", "  File \"C:\\Users\\isaul\\Documents\\Intro to ML\\mooc-fi\\mooc-data-analysis-with-python-2024-2025\\part02-e14_vector_lengths\\src\\vector_lengths.py\", line 11, in main\n    print(\"func\", vector_lengths(vector))\n                  ^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\mock.py\", line 1134, in __call__\n    return self._mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\mock.py\", line 1138, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\mock.py\", line 1211, in _execute_mock_call\n    return self._mock_wraps(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\Documents\\Intro to ML\\mooc-fi\\mooc-data-analysis-with-python-2024-2025\\part02-e14_vector_lengths\\src\\vector_lengths.py\", line 7, in vector_lengths\n    return np.sqrt(np.sum(a**2, axis=1))\n                   ^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\_core\\fromnumeric.py\", line 2466, in sum\n    return _wrapreduction(\n           ^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\isaul\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\_core\\fromnumeric.py\", line 86, in _wrapreduction\n    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"]}, {"name": "test.test_vector_lengths.VectorLengths.test_no_scipy", "status": "passed", "message": "", "passed": true, "points": ["p02-14.1"], "backtrace": []}, {"name": "test.test_vector_lengths.VectorLengths.test_performance", "status": "passed", "message": "", "passed": true, "points": ["p02-14.1"], "backtrace": []}]